version: "3.8"

services:
  backend:
    build: ./backend
    container_name: tsn-backend
    environment:
      - SERVER_CPU_CORES=4
      - TASK_PROCESS_WORKERS=2
      - APP_BASE_DIR=/app_runtime
    ports:
      - "8081:8081"
    volumes:
      - ./backend-runtime:/app_runtime
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tsn-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
